---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.17.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    gatus:
      group: games-minecraft
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-minecraft-proxy"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
  
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${MC_ROUTER_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          main:
            enabled: true
            protocol: tcp
            port: 25565
            targetPort: 25565
    
    resources:
      limits:
        memory: 1Gi

    workload:
      main:
        podSpec:
          containers:
            main:
              imageSelector: image
              env:
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                RCON_PASSWORD: "secretrconpass"
                TYPE: "VELOCITY"
                ONLINE_MODE: true
                MEMORY: 512M
                INIT_MEMORY: 512M
                MAX_MEMORY: 512M
                NETWORKADDRESS_CACHE_TTL: 60
                REPLACE_ENV_VARIABLES: false
                ENV_VARIABLE_PREFIX: "CFG_"
                # GENERIC_PACKS: "configs-v9.0.1,mods-v4.3.6"
                # GENERIC_PACKS_PREFIX: "https://cdn.example.org/"
                # GENERIC_PACKS_SUFFIX="".zip"
                # JVM_OPTS: ""
                # JVM_XX_OPTS: ""
                # PLUGINS: ""

    configmap:
      forwarding-secret:
        enabled: true
        data:
          forwarding.secret: |
            ${VELOCITY_FORWARDING_SECRET}

    persistence:
      configfile:
        enabled: true
        type: configmap
        objectName: minecraft-proxy-configfile 
        expandObjectName: false
        mountPath: /config/velocity.toml
        subPath: velocity.toml
        readOnly: true
      forwardingsecret:
        enabled: true
        type: configmap
        mountPath: /config/forwarding.secret
        objectName: forwarding-secret
        readOnly: true
        subPath: forwarding.secret
      config:
        targetSelectAll: true
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      server:
        volsync:
          - name: server
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      plugins:
        volsync:
          - name: plugins
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
