apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minecraft-bluemap/ks.yaml
  - minecraft-proxy/ks.yaml
  - minecraft-stats/ks.yaml
  - minecraft-java/ks.yaml
  - minecraft-creative/ks.yaml
  - minecraft-lobby/ks.yaml
  