apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - minecraft-proxy/ks.yaml
  - minecraft-fam/ks.yaml
  - minecraft-creative/ks.yaml
  - minecraft-lobby/ks.yaml
  - minecraft-phpmyadmin/ks.yaml