name: gitops
working_dir: ./docker/seb/apps
auto_discovery:
  enabled: true
  depth: 0
  delete: true
env_files:
  - /home/xstar97/docker/cluster/docker/seb/secrets.enc.env
force_recreate: false
reconciliation:
  enabled: true
  interval: 3600
