apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:hChdCgycGmdKAZY/AzWOPeT3CV3yXs/fxkoSIy1r+YcCLZFo4mgV/LZ5a4kUPWQtIS/yphRwBdVr2okeAH2owDOFnEpaZD5iU5z3AcI6ZV68y3Ju7nfYU0ssMCXfMPuhTBKFMV4U48rbP80K7uPvvc/7u2VDuiydsxXCzg==,iv:WchiyN6CHKiyOVrsSiWEplCGvngVT4HkwwbK0eWX5i4=,tag:ksemqsLl2q8P9RFzaGMbng==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYUVEVmR4TnRxRkhvNStD
            TE9ONktpSVhCck51SkhVL2hMbFRjbEJrMEZVCmtqd1IwUmlVa3EveWc4cTZLUnhB
            cXRRZVY5QmltMW1HM3RWL1IyVDA5SzAKLS0tIGt2QnMwS25LYWlSdFhpV1JTM3Uz
            WVh4TlpYcjB2c2h2bzdlM0lxTFZwamcK4gHEbuo6SlYRimugRQEDqTVv38eoLXtA
            XsAxssbXUj68DfTfIpu5lf7ZlbRwYbNwwCT7H60KjA+7x1bGHl438Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T12:42:33Z"
    mac: ENC[AES256_GCM,data:+zYwM4DjjjxiS9lA/+KdhWkvQ0ZFJhBACuD4c7fyqDDo82POmPl4YiNskpb3SQ8DyszLr7aNpS4Yyf6DoF8a6KcwTFHX9ihIPyylrWsYI+MYaIeh6oDNk+vVXSdCGJMexOihSTPdBo67vphl8fjUkUzArYyYrmmwD3DwawZWTA0=,iv:pMUBxRm1+8nJ9ArEMPZg9sNdFa0qsocojyErMgmzPkA=,tag:eIG63oyHYaMP4BIaeDwOFA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
