apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:Jsn/4P6DZ7HVj3NUplhahnXAuEmlanWRDyonoTLZvhaY0B69gJcnWD4rdjSs9+IVz9lCQ7NGk+MGbCsghh5hK/FMVov8GliSQcayfMsZ67x8OSLEKIE4RDPTT8tm0GC8klCbOMzKLf8KcGjoN2381XsPd2+10jCvOHa+7A==,iv:78V7yhLSxvLW+7cLHl04/zuvsMLpR0AyYGjqFu3aGjY=,tag:RoHytOUH2M8lO0vsILY/Rw==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZjJEQjFWelpmZ3RxWitu
            Ukkrcld2V0NWbHRHcmVLTU9CMlpwOGRoOUhRClJpbVRZSmtYRm5Ccm1wTFJrcllr
            Z09qS2cwcTRzV2Mxc3l3dWJwcmFsQk0KLS0tIHRXRGg1OE1weDBlaUw3bG9SbXhU
            U3A1SUI5Q0FIR2RZYi9OV0dGRHpSL2sKOx8fAei705rl+kNmfoqjDJizmWyQtdjG
            KQ91weVi3hd8wtKGs5hXJMY6uKzFXW2q5OcZOpK5lVCrC8uoob6jFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:25:43Z"
    mac: ENC[AES256_GCM,data:VtuR5uFaiKizmfabZ6O/B/+JLWzTKV237VpsrtAPls4NVw0UpK9vy3sq1xvOote48iCfl0o8OG8vpaEkkBsSazKixYVcjEguZtMI6a5rrhesM2ROyBGFNmJJtx2oR34AvSXVwlFCNY2Z2gByup1l2kOF9qCSoesCqg57TNc8N/k=,iv:sTYURmyJ4N87Ji61EEhNZYLmEZEDklGWz9kSQUXW4zU=,tag:goZLp1FJiGCbeHQTburSGQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
