apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:YsoHa1/NqsFYegxDUraNG1JMQhuLAbyvnDzzg/ExCgf816lgXzCt1OPKpDXMXeegP5dKhJmqGeDzoZxydWHGToFkFrxGBJ2M5oZdyNVNY+ObKaJ1Ln7IUrsb2o3mBGErpbZ39Bp6m8Wit7zluSk9nkFi+j5bq/RBsgrqfg==,iv:aO5eWP6+Zqqhntc9DDNaCnQ5vu1pBc3QKTzXEdtJC+w=,tag:W1YA4HWmB3V/T7a9kkyOnQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age173y4f2c8lc5lrf3qjrzle0653fq2l8565u6at52gssfd7lwzeqhqpuuv2r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNWs3cndYWFQ0elRSV0Jy
            cXFVVlJuaC8vZ3FJQzhZRTRJOTMwODZodG4wCm5oUXlSUTB6RjRlUitVbS9TYmk2
            MTRKVURNa2ZFdms5TFV5Tm9nc2YwcjQKLS0tIEpQM0tBbnRxdFYyRGhjbjJmY3pF
            N3BsNm83dEtZOUVDVm02cnhTbVovcUEKtNC2bclbw9OOnqNJg08ck8b8Whkb3QNw
            uJDwhnNa5s4nGG6e6qI0g1vuFiBnjzhGxbvKIIuR3orF6szo+w0CUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-06T09:36:50Z"
    mac: ENC[AES256_GCM,data:a+gDDu/zHhOO1RSoO4GIS+D9rq0MOK8Zveg/VeQKbFfEXH9WJGCYZ39of5SfMZUkUsFESj00lw5zyTxETiSpEDFUipAchZFIqn8DhjfbkSVUGV6lTQu1GU9onJVZVqAEFcB8TeMS2QW+K19xMpN78ob1a5NfYA+6ixveafmZH0w=,iv:G7X0JbKee3FI5CsD+s0u1T5KIl8wCk4wZ572BaYlJQI=,tag:u39J9sFfE9phSHoGnUMq3A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
