apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:cLqaW9zTUc7mc6OJN6eaObFVhT/q125cQPo9Vy/fJiQ=,iv:Ks9c5Yaj30iNsFxBaS9wPDM1DcG1bPfSCxfGoYopn6U=,tag:Wqz+PwFIWVN8ehNxdhqHHA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycHBhUzhPOWJWQ2NFc0x1
            Z3R2SU40d3hLQTB3encrZHdNYmlKZ3k2QldZClY5WjdxK1JieVZoNjRQbFJYNTNI
            ZXRkRXJGZC9DRnl0dUZPWnpabFlZVUkKLS0tIDBwZWdjSHIvb2RCcHEzajJ3bjRG
            ZHM1aVZGN0R4a2FPWE4vUzVBaDJjRjQKStaoOR3ehYsl1+hzURkNPqTtv3LDjW3m
            Z0Kg/wkCXP73UPVxdlJZeHXUjmpycBAo3IOi6ZiCGPi5Lmu5uBSrNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T08:17:30Z"
    mac: ENC[AES256_GCM,data:dCnnPRdzRS+Bhq/zcDxRSNrumJnfOaiUqs36+BOvYpnxpi7UTw8iTBkaOsU5eNDEK4pJndXjxsQRbsq0EpO19R5A8zL9wsDSNh/lXHGYQNvghKWacTdIQlaE2z1CfPXqCmqcLR9A2II4MsQweFpn3WuFIBAAauQph14cY6UzYfg=,iv:+OrZBLAehYOCVQA5G5olPEhoyxtle8N8xEYJlOwAfzE=,tag:1n5Z2EsdL6l17fJhvD3tmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
