apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:3q/ACrUmoTojLWDNTFFBKVrpRYgWOMOTmhaIaNMDbfg=,iv:mRkMDbP1EimZ5wEzJQn4XDhxQ3+D3E6yvOElfk9RQD4=,tag:TtSio6EfIZ9QSTkH/l4AEA==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSFYzczlKOFpNK1BmODFS
            NGxwbXBVM2JBU3dkRnNRV0tWTjZ2UjY0TEc4CkNSTlNGQmRJYkhtYlJDcTIxZENQ
            M1Rvbm9tTEZONjBuNDB3UzYrdEpqQWsKLS0tIHpucVF4NkN2eFExVytUYWZGR1do
            YVQxOUs3eGJadGppdXRZMnVjOWR4ZU0KLTkU2ghu7M45K5lrkPbsBX5CAk/Kqa1E
            IyUYb6t34iG1Z5iLyo4fwTb9R97DgB5QAcLBjRmLFljgeTktSlzU6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T04:42:08Z"
    mac: ENC[AES256_GCM,data:hnRWA3+ipc5YKf8nJcKYV9a/Gi3rjhZKsHFrwuMoeaR5K8JpcDzmkMPhudR0oufKHPNNh5gUwmyFd8fXz1TEXC6RzEQeMvbzdxqgYdEaPZOH13jiMZRkuf66xMPME7/fQ4eiiiKZ546vdaFJsZv1cvJ9C06zzjoLxXL9CnESyHA=,iv:+8AbZdt/paO5HovdJ2vfEITBlLDdnlLEWEXJ2i9rCok=,tag:rtXx+715a4R82ZyWa8I39A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
