apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:UKvFxuE+FUXKAWLUnlfWnpmGFHu5KTNLqFTbYe03R0o=,iv:NWqOQP/MR8TE+zT4T4+7WuODuGm8aBOikdYgoo5ZWko=,tag:vL8Dvgzoij5HHU2VI0grqQ==,type:str]
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcjRxVitwbE5xWlRJaTdI
            c282TE5HNFdVN0g3OWJyZWNsc21SdHBadlhJCjQvMjRXcGZBd1puajhtMjFLWndq
            YXEvVEdwd1VWRXg4eGRpcnZnSnJ1d1UKLS0tIHV1WDhBMWU3cXJNanpjTTJqU0tn
            ZWl6T2hqeDNLTGJ2c0oyaUpoTDZTVW8KbWj82A+TfJ1iR/P6CzZxoW0cBBmJFdAe
            NeFHiZ6gmKVqRwEBBJtRaq0ybkqwHHMj5yo9YvDcx+kPMn+bPeWM1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-22T20:25:43Z"
    mac: ENC[AES256_GCM,data:qiEL3dQs3vNg45G4Z2LKCWHdoTVxsnr9t8k0hwTjGqOQUNljIuN5NRC0Qc8yQym4Fy5ZvajbkABtYOl4FrM4B28Rb/3BuSNBJa/+5UY7VzK0K3HYGWA/1yZJBD1OU1WeXGNjFB6RVnAhCIdgE6cjCdi28o80tnSRvMy0CoHe2HY=,iv:e2+MWXmyzRXgQfM5oZ1LBoD6w0HR7/b0O/QKPC1rI7Y=,tag:wZJHHSifZUDadUYtghkVTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
