apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+/9NsuR8MeSYqZk9/xi9B+IjOC0WaKfhNj+W2+2QFkM1KuQVscrtZ7YpHmnG/HcDr993XImt2YT4yJe7+bKBFYwCR/qBZ8Lk26jX4QqKqvC4TpXaFRbiZOdfS1Ay0uwYIf48wbngWSd4gEIH7VBYxl0oOmsU5BlK07gnLGu2ms6MEZoW1vF/1H8eCf9gcpMXJy0fGhLZQlI1ArAtHFX1hH2+AN7W2K3hQmbl/z4Ly6f+MsE8PejIfBlIZEgtsG/nVB938q3eHTOyuYnGVl3MkJCrKdn0FXXceupMfQsNJtae6Ln3d6OEm0/9yOtxjaVShIOp8vhUzEZGSDcBtCAavK4esJHVEaOT1BLD9CP3/p+s4Xn2yESPh7WGC86aV8wE,iv:pzJq1IkIE7trbf9c0s5l5UmmytcDPHdo1aDDLKXIDY4=,tag:F//QKPRQot9JwmBMArF8wA==,type:str]
    identity.pub: ENC[AES256_GCM,data:vAGg1OpVCveUYWsM3hFmFq/TZsZNHb0u9VW/cfZZ/w17Qlogp8ZB4S/MHEZZNJ/yAUfGVXMTBVgbl7KyD3pdCTMEEUjjtRczeOfbpoDeX8iEUOUeHo/lWtO+TzeYKARdIBMxP/xXpehJdkQ/1mJDONCzaUWTmVBk6MOBnStJV1OvKahJNpmstY57vLe32TlhpX/RD4D8ZukWLcwhaC6Yb9kmsUN4FprIYbNaT8kSdYUB78BoxgGau3sJuZJbodY+bcJYDnwMbMFN5IS/lg==,iv:7MoUHKFmv18bFjz2oZqV/Cer2X7i8mFnFWKUKnBOlPY=,tag:Yi8YAu2ku4Z0MVjmqexfkA==,type:str]
    known_hosts: ENC[AES256_GCM,data:J3iHSxqROmaW1FTkAi5lbwXcmsyaFJid9wLoZ5cuMbmS1JefO7Wjz1VolFgGih+KknBRMUYZXHOjbPJlWlEh+lVqfGvEAzf2HAfmx+FaGQ8vENtMO9tYeimiGr4L2faLGFIBHHe2lzaCJgn3hs/Jjuf/A1/4uPBB+rMLqIjXbb8WznT/8AdaZ9Uy8pUqWp1FvJEFLLSpk+hqejvpWYjtS/kZ35Kz5AoIMFCx,iv:/GVHEm6moj0Hj0Nnvw9aNLHqrliBZ29HJMbiOwQwGrM=,tag:nmk1IX42sCHSsWZNhRlWvA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age17rkne6kdscvdcp007yr0yjjnkscqwr9jvt8sz3wy75qema3c8d4q8f05nl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUlJua1NBMS9yWUpBVnZp
            UFF3Q3FRL0tieGl1N1B0MC9DaXhtMVdYK0NjCjRkYzBCTnBlMmk4b0k1S1k5bmYx
            bG1KdmMzdTQ1dlZxUzNiaWMrM2drQVUKLS0tIHlnbVMrMjNvUi9taWNDNERNY0pC
            OHNuWEJEU2ZxbTN5TW90a2c3R2FRMmMKSAVTcLfshn9HHgCnr8/PS5B6LX7srlM2
            cgluEzFempMnQoSKOMgJNqVltw1wks7bgr3AUW7qVidEDO8o9OR39A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-09T04:42:08Z"
    mac: ENC[AES256_GCM,data:a9UH+F2htbN993Zts7QItxt3tUuDoAxzehrKZ80EgldT8w5WuEd87R4EOMifS2p4449pEEFzebnoQ7YeOm72rSbTAWg+/8IhraVsbZNmzuCRvPhwjdn2ixdtuLacWiF/FFzB8yNYMrtGHj97KjPRu2S3k6x32W1H4Cqz04/5/4s=,iv:0LGnIhRAfgVXmGHBsEywk6i6v2BnFTXZeFWvgmRdFzo=,tag:FMNMl9b2GLKLhu4AjaMLJQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
