apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8Wl7c843s2qxJvhfYFc+QZcjYahY+gT73r4KH4scZLNtrjytJUQEjwB1j5tC1xPgJwMOEy7VA0lme9NFfoDn35bYn8mAPqU+Dys9uTXbY1cCOMtNKJ2HJ07eG7/4XMVQ9nxWEK9fjmMmrNNCOdo90e7KHLuE8rctICq7q/PQUhOyQ2CjrSJ/PJP3kB72OWHjUrlmu5558HFTf6ioW7S4+QRo97IFS1PmpJzAEVc1wQVNUAXMSTTwp4EO9J2gdq1fmVIcgYzNVD1JRGx9wIYK6udG7OKzdYedM5Hw7ojNHNomWZlOl9iLl5w6KwrOdAQ4M2ky+X6qbe7gg/SGl2PGGukXDIvNd28L6WZ5Ac11GiC8R9kxMXWKEAGnqNEgbFbD,iv:MK9BIkKrKE7KTm5O0+yoZQAICgK1V7kjOHK6Fuu0wA8=,tag:VHpzW7SKMZ1CncasSPdBTg==,type:str]
    identity.pub: ENC[AES256_GCM,data:WgdniNtLgnioAYIr5PiJmahDcsJ7YeM+iox1Z9ix31xcPj5e5+Me4BN4iR4KRvthqejEQ20lqz07AgocPQBD6E9B+Tc3r2a0iXXnrWURRp1JwNpiWRLCbSEonIT2XHprwsFspTmSzLuheSmqYu03qxt+VmOLSwgfMoQuI/PsZrI0r1RtbFlfNiSsTR0YH0g0+HXW4xagWA1A4ls7iCNwWuL/Obhbtkqc45IqV5cDzO5m9lY7X5jwijEwiNL521Ju1Gfw3k2B38KLfkaDzg==,iv:eUt2x86ZLxFFsq0BEbe4qQEWDAoksI8a+8wN1Z07lI0=,tag:wkYN9klCvE2SomMp6nuwoA==,type:str]
    known_hosts: ENC[AES256_GCM,data:ZKrn5lJNmxKVCki6mg2arqM8vpNO+IaD80TeAoJoFQ7sOWWQwC2+l53iJoRKl+rX6tSuDpB7gJ0tapvMXFMM2EdQz5Z23QHeUyrIPksjkSaffEkGGhqKEV/trhWExQRWBcetHrvRJZVxDB2CDM7yjau5Khpgu1M6gjca2w4WkRqBdCEphfQGDyFtMN1RLrwtNO8rylJ+aIvJqPfGQfJ0ExgiBz2gAmcvURnN,iv:qnsp2Qwhu0dSSp0PLtNVoWlR1dpPqk3yocOMkGbB/Ow=,tag:WYnuNvmALsYgyqCmMybroA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age173y4f2c8lc5lrf3qjrzle0653fq2l8565u6at52gssfd7lwzeqhqpuuv2r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaVMyTjVhRWg3THlkS2Zr
            cDhWTmN1V2Z1aG5xcXJjcWwyYkh5ZjMvTVRRCm1SOS9xZjZpbm5YbUFCOE8wbzZo
            citYdWk3YkFrVmp0U05OSE1VMzJlaHcKLS0tIE9MbmlQdWRENGw0OVM0N1VieUNF
            dDVlUVZ6SWRQUmZDZVYxbkVFMXVpblEK+8yptilIr8VxE7Bngp8t9Sau8UlV5DTm
            YsWUp5W09fhu5LVVyKbDLoznTfAUqAtQDttq12lBKlRvok4WiOK5mQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T12:40:25Z"
    mac: ENC[AES256_GCM,data:FwwPyEbw83/VRtazgLlDnABkxRoLtY/2YqZiqd8vt7ZoL9qnLc52z8O15kL9ZFULEGd/KLmB8Rzd8XBt4wphaZzFUfQWrbzwmTmNw6EOSgs8tQcQE2FKrSrM9ku8DbYHZ3ZvTCo/PI5A32LSEte+YeFUpmREK8p5AEFxMlasW4I=,iv:x3ler790y6995EDaGQ2vglrw0mRuU6iLC2LZm5ndKg8=,tag:T4bOCHUYvCVUF7Odc6cjEw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
