apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:IL7XCw80lykidzoKErIWcoMTjlmwaqasMqZjG5rtaYk1NEquFVR18hRV8BI8jVMASL75zAA6Ak3gh3PWVR9gYiKA0P4sEKFG4tWRyda4WN4lVPlrYNTwUj199idbLot3qfZmwKilYnsBigp/VGaOrTt0zYI0f9NXK+14mNeqZODnTFAIhj5hkGJ1yKtmKkCgefGU61F2so+wlXa2uuhW0ck576Wbco3QxkxkZ/R09GoAiOZnkAVT4bch+LT6faTHeq5kIRADlnkuTSb6yJA6bWe8WL9YP18c8Ob1ttsSb+L6qNC4Bvz9EcC0tTYdg/DmAXVWWmUMeRaTCS6gT5cNLL1ibIGqp7l6Fcs9+Umxl/b+A68Ce25OYazp740tgW5+,iv:6kuuaKv5uI8Yi0K2N02ifhQIF5KlnfSVQF7Ny4WKU98=,tag:6ol6joWcgBwVCJI5OiX3JA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5aJTGCKdznK0gqciFaCUW4bqrMWNEZjcffD3sGXiyYsmwY81gAwtIn837xNDibY9/4Qh2etQwJxGWBqM6QJzfpjBO+nXJg2e74ZW7IXIUYoImSBcEGw2HsMat4RHNc4ocIDQz/CF5dISpJxE1Y2dlfMWDgrEezXGo3klSXcr2bF1CTw5D9RX8jKAJHGLhjy/ib+3SAsjseRR1/hJQq6eKI9oHq81KCrzrjSersMb1qA0AA4ww61dwoU4Dvk+wWkWY+IfUkMYNx/h093kNA==,iv:l478lb/pWXAGTgyp8RrPtiwpxZ4gd714LE8EfSIiEyM=,tag:0j3IVjKupvAbQz2rLr2+ow==,type:str]
    known_hosts: ENC[AES256_GCM,data:zNvG0mn90SUcqpDjR017jQ75iJ5b0DD0mmyqbbKhc7motE4kYAz7EeNq24CLnalfHrCpZs93MxG073+eNdNiV8+RZAu/MUqBVKDpDLipulsYI3okf/X8dAI4fAoW4cuF7fLcLEO3d+ITNQBjKin2q/vRtpd4O0YbeQ3CxqL+4IAd/InLMdyo8P8PhUrELftN5g/L+eqq4XGNL54nv6hTBskRfj6ZCMLAzDLR,iv:7QS6pJgRYwVeDjomMdbQjJE4ksDMaLs7qoDIWcxTUqo=,tag:j9yuh1SsHhDUeAkRN+N/xQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age173y4f2c8lc5lrf3qjrzle0653fq2l8565u6at52gssfd7lwzeqhqpuuv2r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdkFsTmRiSmU5MnhjNnVW
            OTVkd0pNRUVsL1l4NytkVHR6cUk5dXRBV0RvCm9BRnFhNTJEcE5tZEpZSjhCOTJ6
            UW1yaFBMSms0c0hwZXN5bFZZWnB3azQKLS0tIFZSa3lva0tGaTAyaGlVcVQ0WmVB
            VUdKT3VhV2ppRC9PSjd0dUpOR2QvYnMK6BpMYPL2KuaAt79doNEIo2DfFe0PvtjA
            YjpO0Bzaq7V+/G9wo5/JbQl1yzcFD+fHppHeeaMKa1k8SqBbmHBEYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-11T13:16:37Z"
    mac: ENC[AES256_GCM,data:ojw+yU9Df0eUd55DxYlnNZMoxuyI8j+kqIsXEjlWSaf/vAIG0DPSbwcMR1JGplbDGjkXirTyE0IZUTu7aUicP3pjq5CSEnu1kwoz2w0GeSVBwpx/538tI0lXcSlDBNW0o5QU2YxmdnqNOO6UocNnEzgO5S+n/YnhpkaePXNWT1U=,iv:b9hXWyGDDu3nlXBO956a7N1enCTZO/pZ6BJBIihbpuc=,tag:tZenmsO5E4NLUAvGAgtOqQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
