
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway
components:
  - ../../../../components/notifications/discord
  - ../../../../components/ns
  - ../../../../components/gatus/service
resources:
  - helm-release.yaml
  - envoy.yaml
