apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: librespeed
components:
  - ../../../../components/ns
  - ../../../../components/notifications/discord
  - ../../../../components/gatus/service
resources:
  - helm-release.yaml  
  - security-policy.yaml
