---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-java
  namespace: minecraft-java
spec:
  interval: 30m
  chart:
    spec:
      chart: minecraft-java
      version: 34.0.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 30m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # image:
    #   repository: ghcr.io/itzg/minecraft-server
    #   tag: 2026.2.1-java25@sha256:44aacf3902c1c2e18dddfe8585dd44badbf56a0a768c773a5e0bcfe4bc1d0443
    #   pullPolicy: Always
    statsImage:
      repository: ghcr.io/xstar97/mc-stats
      pullPolicy: Always
      tag: 3.3.1@sha256:a9fae5944ad5a6d7aa90f8f34a7e0bc413eb8b3a714b6089400b1e66cd00e7f0
    gatus:
      group: games
    global:
      stopAll: false
    credentials:
      cf-restic:
        type: s3
        url: "${CF_S3_RESTIC_URL}"
        bucket: "${CF_S3_RESTIC_BUCKET}-minecraft-java"
        accessKey: "${CF_S3_RESTIC_ID}"
        secretKey: "${CF_S3_RESTIC_KEY}"
        encrKey: "${CF_S3_RESTIC_KEY}"
    securityContext:
      container:
        readOnlyRootFilesystem: false
        capabilities:
          add:
            - CAP_NET_RAW
  
    service:
      main:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: ${MC_JAVA_IP}
        integrations:
          metallb:
            enabled: true
        annotations:
          mc-router.itzg.me/defaultServer: "true"
          mc-router.itzg.me/externalServerName: "java.${DOMAIN_1}"
        ports:
          main:
            enabled: true
            protocol: tcp
            port: 25565
          query:
            enabled: true
            protocol: udp
            port: 25566
          bedrock:
            enabled: true
            port: 19132
            protocol: udp
      rcon:
        enabled: true
        type: ClusterIP
        ports:
          rcon:
            enabled: true
            port: 25575
      web:
        enabled: true
        type: ClusterIP
        ports:
          map:
            enabled: true
            protocol: http
            port: 8100
          stats:
            enabled: true
            protocol: http
            port: 8080
    
    resources:
      limits:
        memory: 8Gi
    plugins:
      # vault
      - 34315
    modrinth:
      - bluemap
      - viaversion
      - placeholderapi
      - clickvillagers
      - clickmobs
      # - theclanforge
      - packetevents
      - holomobhealth-packetevents
      - holomobhealth
      - chunky
      - lagfixer
      - customdeaths
      - discordsrv
      - networks
      # - bytesessionrestore
      # - storagev3
      # - regensystem
      # requires protocollib https://www.spigotmc.org/resources/protocollib.1997/
      # - customdisasters

    mcstats:
      server:
        sources:
          - path: /data/
            worldName: world
      data:
        documentRoot: /config/greenefam/public
        eventsDir: /config/greenefam/events
        statsDir: /config/greenefam/stats
      crown:
        silver: 2
        gold: 4
        bronze: 1
      client:
        defaultLanguage: en
        playersPerPage: 100
        playerCacheUUIDPrefix: 2
        serverName: null
        showLastOnline: true
      players:
        inactiveDays: 7
        updateInactive: false
        profileUpdateInterval: 3
        minPlaytime: 60
        excludeBanned: true
        excludeOps: false
        excludeUUIDs: []

    configmap:
      plugins:
        enabled: true
        data:
          plugins.txt: |
            # https://github.com/pdinklag/MinecraftStats/releases/download/v3.3.1/MinecraftStats.jar
            https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
            https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
            https://cdn.modrinth.com/data/HQCF0DEG/versions/HlwiKb4T/DropperAutoCraft-0.7-SNAPSHOT.jar
      stats-config:
        enabled: false
        data:
          config.json: |
            {{- $.Values.mcstats | toJson | nindent 2 }}

    workload:
      main:
        podSpec:
          initContainers:
            update-config:
              enabled: true
              type: init
              imageSelector: "image"
              command:
                - /bin/sh
                - -c
              args:
                - |
                  set -e

                  mkdir -p /config/greenefam

                  cat <<'EOF' > /config/greenefam/config.json
                  {{- $.Values.mcstats | toJson }}
                  EOF

                  echo "Wrote config.json to /config/greenefam/"
          containers:
            main:
              imageSelector: image
              probes:
                liveness:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
                readiness:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
                startup:
                  enabled: true
                  type: exec
                  command:
                    - mc-health
              env:
                SERVER_PORT: "{{ .Values.service.main.ports.main.port }}"
                QUERY_PORT: "{{ .Values.service.main.ports.query.port }}"
                RCON_PORT: "{{ .Values.service.rcon.ports.rcon.port }}"
                DISABLE_HEALTHCHECK: true
                SERVER_HOST: '{{ printf "%s" (include "tc.v1.common.lib.chart.names.fullname" $) }}'
                ENABLE_SSH: false
                WEBSOCKET_CONSOLE: false
                WEBSOCKET_ADDRESS: "0.0.0.0:8080"
                # WEBSOCKET_ALLOWED_ORIGINS: "*"
                WEBSOCKET_DISABLE_ORIGIN_CHECK: true
                WEBSOCKET_DISABLE_AUTHENTICATION: true
                ENABLE_RCON: true
                EXEC_DIRECTLY: "true"
                ENABLE_QUERY: "true"
                EULA: "TRUE"
                GUI: "FALSE"
                OVERRIDE_SERVER_PROPERTIES: true
                VERSION: "1.21.11" # "LATEST" # "1.21.8"
                TYPE: "PAPER"
                # PAPER_BUILD: "138"
                DIFFICULTY: easy
                MAX_PLAYERS: 420
                MAX_WORLD_SIZE: 10000
                ALLOW_NETHER: true
                ANNOUNCE_PLAYER_ACHIEVEMENTS: true
                ENABLE_COMMAND_BLOCK: false
                FORCE_GAMEMODE: false
                GENERATE_STRUCTURES: true
                HARDCORE: false
                MAX_BUILD_HEIGHT: 256
                ENABLE_AUTOPAUSE: false
                MAX_TICK_TIME: 60000
                SPAWN_ANIMALS: true
                SPAWN_MONSTERS: true
                SPAWN_NPCS: true
                VIEW_DISTANCE: 16
                SERVER_NAME: "The GreeneFam Server"
                MODE: survival
                MOTD: "Welcome to the Greene Family Server!"
                PVP: false
                # minecraft:normal
                # minecraft:flat
                # minecraft:large_biomes
                # minecraft:amplified
                # minecraft:single_biome_surface
                LEVEL_TYPE: minecraft:amplified
                LEVEL: world
                ONLINE_MODE: true
                MEMORY: 6144M
                JVM_XX_OPTS: "" # "-XX:MaxRAMPercentage=75"
                RCON_PASSWORD: "${RCON_PASS}"
                USE_AIKAR_FLAGS: false
                USE_FLARE_FLAGS: false
                USE_MEOWICE_FLAGS: true
                DEBUG_AUTOPAUSE: true
                SKIP_SUDO: true
                REMOVE_OLD_MODS: true
                PLUGINS_FILE: "/data/plugins.txt"
                SPIGET_RESOURCES: '{{ join "," .Values.plugins }}'
                MODRINTH_PROJECTS: '{{ join "," .Values.modrinth }}'
            mcstats:
              enabled: true
              securityContext:
                container:
                  readOnlyRootFilesystem: false
                  # runAsGroup: 0
                  # runAsUser: 0
              imageSelector: statsImage
              probes:
                liveness:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.web.ports.stats.port }}"
                readiness:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.web.ports.stats.port }}"
                startup:
                  enabled: true
                  type: http
                  path: /
                  port: "{{ .Values.service.web.ports.stats.port }}"
              env:
                PORT: "{{ .Values.service.web.ports.stats.port }}"
                INSTANCES: "greenefam"
                INTERVAL_SECONDS: 300
    ingress:
      bluemap:
        enabled: true
        primary: true
        ingressClassName: external
        annotations:
          #   nginx.ingress.kubernetes.io/configuration-snippet: |
          #     rewrite ^/stats$ / permanent;
          gatus.home-operations.com/endpoint: |
            name: minecraft-java-map
            group: "{{ .Values.gatus.group }}"
            alerts:
              - type: discord
                description: "healthcheck failed"
                send-on-resolved: true
        targetSelector:
          web: map
        hosts:
          - host: map.${DOMAIN_1}
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
      stats:
        enabled: true
        ingressClassName: external
        targetSelector:
          web: stats
        hosts:
          - host: statsmcjava.${DOMAIN_1}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: general-le-prod
    
    persistence:
      plugins:
        enabled: true
        type: configmap
        mountPath: /data/plugins.txt
        objectName: plugins
        readOnly: true
        subPath: plugins.txt
      data:
        targetSelector:
          main:
            main:
              mountPath: /data
            mcstats:
              mountPath: /data
            # codeserver:
            #   mountPath: /data
        volsync:
          - name: data
            type: restic
            credentials: cf-restic
            dest:
              enabled: true
            src:
              enabled: true
      stats-config:
        enabled: true
        targetSelector:
          main:
            mcstats:
              mountPath: /config
            update-config:
              mountPath: /config
        volsync:
          - name: config
            type: restic
            credentials: cf-restic
            dest:
              enabled: false
            src:
              enabled: false

    addons:
      codeserver:
        enabled: false
        service:
          type: "ClusterIP"
          ports:
            codeserver:
              port: 36107
        ingress:
          enabled: true
          ingressClassName: "internal"
          annotations:
            gatus.home-operations.com/endpoint: |
              enabled: false
          hosts:
            - host: editor.java.${DOMAIN_2}
              paths:
                - path: /
                  # Ignored if not kubeVersion >= 1.14-0
                  pathType: Prefix
          integrations:
            nginx:
              enabled: true
              auth:
                type: "authelia"
                internalHost: "authelia.authelia.svc.cluster.local:9091"
                externalHost: "auth.${DOMAIN_2}"
            certManager:
              enabled: true
              certificateIssuer: general-le-prod
